import type { PresentationAppDefinition } from "../app-types";
import { createJsonAction, createTextAction, createNoInputAction } from "./action-helpers";

export const TOOLS_APP_DEFINITIONS: PresentationAppDefinition[] = [
  {
    id: "dashboard",
    title: "Talend Dashboard",
    description: "Resumen visual del proyecto, actividad reciente y accesos rápidos.",
    resourceUri: "ui://talend/dashboard.html",
    launcherToolName: "talend_app_dashboard",
    launchMessage: "Abriendo el dashboard de Talend.",
    actions: [
      createNoInputAction("Bridge ping", "talend_bridge_ping", "Verifica el bridge."),
      createNoInputAction("List jobs", "talend_jobs_list", "Lista los jobs disponibles."),
      createNoInputAction("Coverage report", "talend_coverage_report", "Muestra cobertura y gaps."),
    ],
  },
  {
    id: "deliverables",
    title: "Talend Deliverables",
    description: "Prepara salidas, análisis y artefactos para entrega.",
    resourceUri: "ui://talend/deliverables.html",
    launcherToolName: "talend_app_deliverables",
    launchMessage: "Abriendo la vista de entregables.",
    uiMode: "react",
    actions: [
      createTextAction("Export deliverable", "talend_deliverables_export_job", "Prepara un paquete de entregable.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob", requiresConfirmation: true }),
      createTextAction("Collect files", "talend_deliverables_collect", "Recolecta archivos asociados.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
      createTextAction("Validate checklist", "talend_deliverables_validate", "Valida requisitos de entregable.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
    ],
  },
  {
    id: "component-catalog",
    title: "Talend Component Catalog",
    description: "Catálogo visual para inspeccionar componentes y sus capacidades.",
    resourceUri: "ui://talend/component-catalog.html",
    launcherToolName: "talend_app_component_catalog",
    launchMessage: "Abriendo el catálogo de componentes.",
    uiMode: "react",
    actions: [
      createTextAction("Scan installed", "talend_components_scan_installed", "Escanea componentes instalados.", "pluginsDir", { inputLabel: "Plugins dir", inputPlaceholder: "Ruta a plugins de Talend Studio" }),
      createTextAction("Search component", "talend_components_search", "Busca componentes en el catálogo.", "query", { inputLabel: "Query", inputPlaceholder: "mysql" }),
      createTextAction("Inspect component", "talend_components_inspect", "Inspecciona un componente.", "componentName", { inputLabel: "Component name", inputPlaceholder: "tMysqlInput" }),
    ],
  },
  {
    id: "command-center",
    title: "Talend Command Center",
    description: "Centro de mando para navegar jobs, logs y contextos.",
    resourceUri: "ui://talend/command-center.html",
    launcherToolName: "talend_app_command_center",
    launchMessage: "Abriendo el centro de comando.",
    actions: [
      createNoInputAction("Bridge commands", "talend_bridge_commands", "Lista comandos del bridge."),
      createNoInputAction("Launch configs", "talend_bridge_launch_configs", "Lista launch configs."),
      createNoInputAction("Recent events", "talend_bridge_events_recent", "Muestra eventos recientes."),
    ],
  },
  {
    id: "home",
    title: "Talend Home",
    description: "Vista inicial con estado del entorno, actividad reciente y accesos rápidos.",
    resourceUri: "ui://talend/home.html",
    launcherToolName: "talend_app_home",
    launchMessage: "Abriendo la pantalla de inicio.",
    uiMode: "react",
    actions: [
      createNoInputAction("Bridge ping", "talend_bridge_ping", "Verifica el bridge."),
      createNoInputAction("List jobs", "talend_jobs_list", "Lista los jobs del proyecto."),
      createNoInputAction("Coverage report", "talend_coverage_report", "Muestra cobertura y gaps."),
    ],
  },
  {
    id: "workspace-explorer",
    title: "Talend Workspace Explorer",
    description: "Explora el workspace, el workbench y el job activo.",
    resourceUri: "ui://talend/workspace-explorer.html",
    launcherToolName: "talend_app_workspace_explorer",
    launchMessage: "Abriendo el explorador de workspace.",
    actions: [
      createNoInputAction("Workbench state", "talend_bridge_workbench_state", "Obtiene el estado del workbench."),
      createNoInputAction("Active job", "talend_get_probable_active_job", "Detecta el job activo probable."),
      createNoInputAction("Open editors", "talend_list_open_editors", "Lista editores abiertos."),
    ],
  },
  {
    id: "context-profiles",
    title: "Talend Context Profiles",
    description: "Gestiona perfiles de contexto, variables y cambios asociados.",
    resourceUri: "ui://talend/context-profiles.html",
    launcherToolName: "talend_app_context_profiles",
    launchMessage: "Abriendo los perfiles de contexto.",
    actions: [
      createNoInputAction("List project contexts", "talend_list_project_contexts", "Lista contextos del proyecto."),
      createNoInputAction("List context profiles", "talend_context_profile_list", "Lista perfiles de contexto."),
      createTextAction("Get profile", "talend_context_profile_get", "Obtiene un perfil de contexto.", "profileName", { inputLabel: "Profile name", inputPlaceholder: "Default" }),
      createJsonAction("Apply to job", "talend_context_profile_apply_to_job", "Aplica un perfil a una spec de job.", { profileName: "Default", jobSpec: {} }),
    ],
  },
  {
    id: "database-connection-wizard",
    title: "Talend Database Connection Wizard",
    description: "Asistente para conexiones a bases de datos y componentes disponibles.",
    resourceUri: "ui://talend/database-connection-wizard.html",
    launcherToolName: "talend_app_database_connection_wizard",
    launchMessage: "Abriendo el asistente de conexión a base de datos.",
    actions: [
      createJsonAction("Build connection profile", "talend_connection_build_profile", "Construye un perfil de conexión.", { connectionType: "postgresql", host: "localhost", port: 5432, database: "mydb", user: "admin" }),
      createJsonAction("Add connection", "talend_add_connection", "Agrega una conexión entre componentes.", { jobName: "myJob", sourceUniqueName: "tInput_1", targetUniqueName: "tMap_1", label: "row", connectorName: "FLOW", metaname: "", uniqueName: "connection_1" }, { requiresConfirmation: true }),
      createJsonAction("Update schema column", "talend_update_schema_column", "Actualiza una columna de schema.", { jobName: "myJob", uniqueName: "tMysqlOutput_1", schemaName: "Schema", columnName: "id", patch: { type: "id_Integer" } }, { requiresConfirmation: true }),
    ],
  },
  {
    id: "secret-safety",
    title: "Talend Secret Safety",
    description: "Escanea el proyecto en busca de secretos expuestos y sugiere migraciones a context profiles.",
    resourceUri: "ui://talend/secret-safety.html",
    launcherToolName: "talend_app_secret_safety",
    launchMessage: "Abriendo el scanner de secretos.",
    uiMode: "react",
    actions: [
      createNoInputAction("Scan project", "talend_secrets_scan_project", "Escanea todo el proyecto en busca de secretos expuestos."),
      createTextAction("Scan job", "talend_secrets_scan_job", "Escanea un job específico.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
      createTextAction("Suggest context migration", "talend_secrets_suggest_context_migration", "Sugiere cómo migrar secretos a context profiles.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
    ],
  },
  {
    id: "requirement-checklist",
    title: "Talend Requirement Checklist",
    description: "Gestiona requisitos técnicos y checklist de cumplimiento.",
    resourceUri: "ui://talend/requirement-checklist.html",
    launcherToolName: "talend_app_requirement_checklist",
    launchMessage: "Abriendo el checklist de requisitos.",
    uiMode: "react",
    actions: [
      createTextAction("Analyze requirements", "talend_task_analyze_requirements", "Analiza requisitos del proyecto.", "projectPath", { inputLabel: "Project path", inputPlaceholder: "/path/to/project" }),
      createJsonAction("Build checklist", "talend_task_build_execution_plan", "Construye checklist de requisitos.", { requirements: [] }),
    ],
  },
  {
    id: "workshop-progress",
    title: "Talend Workshop Progress",
    description: "Seguimiento de progreso en workshops y ejercicios.",
    resourceUri: "ui://talend/workshop-progress.html",
    launcherToolName: "talend_app_workshop_progress",
    launchMessage: "Abriendo el progreso de workshop.",
    uiMode: "react",
    actions: [
      createNoInputAction("List workshops", "talend_jobs_list", "Lista workshops disponibles."),
      createTextAction("Get progress", "talend_list_runs", "Obtiene progreso de un workshop.", "workshopId", { inputLabel: "Workshop id", inputPlaceholder: "workshop_001" }),
    ],
  },
  {
    id: "antipattern-detector",
    title: "Talend Antipattern Detector",
    description: "Detecta antipatrones en jobs y diseño de pipelines.",
    resourceUri: "ui://talend/antipattern-detector.html",
    launcherToolName: "talend_app_antipattern_detector",
    launchMessage: "Abriendo el detector de antipatrones.",
    uiMode: "react",
    actions: [
      createTextAction("Detect antipatterns", "talend_jobs_detect_antipatterns", "Detecta antipatrones en jobs.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
      createNoInputAction("Scan project", "talend_jobs_detect_antipatterns", "Escanea todo el proyecto."),
    ],
  },
  {
    id: "fix-wizard",
    title: "Talend Fix Wizard",
    description: "Asistente para aplicar fixes automáticos a jobs.",
    resourceUri: "ui://talend/fix-wizard.html",
    launcherToolName: "talend_app_fix_wizard",
    launchMessage: "Abriendo el asistente de fixes.",
    uiMode: "react",
    actions: [
      createTextAction("Explain error", "talend_error_explain", "Sugiere un fix para un error.", "errorMessage", { inputLabel: "Error message", inputPlaceholder: "NullPointerException" }),
      createTextAction("Apply fix", "talend_jobs_patch_component", "Aplica un fix sugerido.", "fixId", { inputLabel: "Fix id", inputPlaceholder: "fix_001", requiresConfirmation: true }),
    ],
  },
  {
    id: "evidence-pack",
    title: "Talend Evidence Pack",
    description: "Genera paquetes de evidencia para auditorías y entregas.",
    resourceUri: "ui://talend/evidence-pack.html",
    launcherToolName: "talend_app_evidence_pack",
    launchMessage: "Abriendo el generador de evidence pack.",
    uiMode: "react",
    actions: [
      createTextAction("Build evidence pack", "talend_evidence_pack_build", "Construye un paquete de evidencia.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
      createTextAction("Export evidence", "talend_evidence_pack_build", "Exporta el evidence pack.", "packId", { inputLabel: "Pack id", inputPlaceholder: "pack_001" }),
    ],
  },
  {
    id: "report-snippets",
    title: "Talend Report Snippets",
    description: "Colección de snippets para generar reportes.",
    resourceUri: "ui://talend/report-snippets.html",
    launcherToolName: "talend_app_report_snippets",
    launchMessage: "Abriendo el gestor de snippets de reporte.",
    uiMode: "react",
    actions: [
      createTextAction("Get snippet", "talend_report_generate_snippets", "Obtiene un snippet de reporte.", "snippetId", { inputLabel: "Snippet id", inputPlaceholder: "snippet_001" }),
      createTextAction("List snippets", "talend_report_generate_snippets", "Lista snippets disponibles.", "category", { inputLabel: "Category", inputPlaceholder: "validation" }),
    ],
  },
];
