import type { PresentationAppDefinition } from "../app-types";
import { createJsonAction, createTextAction, createNoInputAction } from "./action-helpers";
import { TOOL_NAMES } from "../../../tools/tool-names";

export const TOOLS_APP_DEFINITIONS: PresentationAppDefinition[] = [
  {
    id: "dashboard",
    title: "Talend Dashboard",
    description: "Resumen visual del proyecto, actividad reciente y accesos rápidos.",
    resourceUri: "ui://talend/dashboard.html",
    launcherToolName: "talend_app_dashboard",
    launchMessage: "Abriendo el dashboard de Talend.",
    actions: [
      createNoInputAction("Bridge ping", TOOL_NAMES.BRIDGE.PING, "Verifica el bridge."),
      createNoInputAction("List jobs", TOOL_NAMES.JOBS.LIST, "Lista los jobs disponibles."),
      createNoInputAction("Coverage report", "talend_coverage_report", "Muestra cobertura y gaps."),
    ],
  },
  {
    id: "deliverables",
    title: "Talend Deliverables",
    description: "Prepara salidas, análisis y artefactos para entrega.",
    resourceUri: "ui://talend/deliverables.html",
    launcherToolName: "talend_app_deliverables",
    launchMessage: "Abriendo la vista de entregables.",
    uiMode: "react",
    actions: [
      createTextAction("Export deliverable", TOOL_NAMES.DELIVERABLES.EXPORT_JOB, "Prepara un paquete de entregable.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob", requiresConfirmation: true }),
      createTextAction("Collect files", TOOL_NAMES.DELIVERABLES.COLLECT, "Recolecta archivos asociados.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
      createTextAction("Validate checklist", TOOL_NAMES.DELIVERABLES.VALIDATE, "Valida requisitos de entregable.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
    ],
  },
  {
    id: "component-catalog",
    title: "Talend Component Catalog",
    description: "Catálogo visual para inspeccionar componentes y sus capacidades.",
    resourceUri: "ui://talend/component-catalog.html",
    launcherToolName: "talend_app_component_catalog",
    launchMessage: "Abriendo el catálogo de componentes.",
    uiMode: "react",
    actions: [
      createTextAction("Scan installed", TOOL_NAMES.COMPONENTS.SCAN_INSTALLED, "Escanea componentes instalados.", "pluginsDir", { inputLabel: "Plugins dir", inputPlaceholder: "Ruta a plugins de Talend Studio" }),
      createTextAction("Search component", TOOL_NAMES.COMPONENTS.SEARCH, "Busca componentes en el catálogo.", "query", { inputLabel: "Query", inputPlaceholder: "mysql" }),
      createTextAction("Inspect component", TOOL_NAMES.COMPONENTS.INSPECT, "Inspecciona un componente.", "componentName", { inputLabel: "Component name", inputPlaceholder: "tMysqlInput" }),
    ],
  },
  {
    id: "command-center",
    title: "Talend Command Center",
    description: "Centro de mando para navegar jobs, logs y contextos.",
    resourceUri: "ui://talend/command-center.html",
    launcherToolName: "talend_app_command_center",
    launchMessage: "Abriendo el centro de comando.",
    actions: [
      createNoInputAction("Bridge commands", TOOL_NAMES.BRIDGE.COMMANDS, "Lista comandos del bridge."),
      createNoInputAction("Launch configs", TOOL_NAMES.BRIDGE.LAUNCH_CONFIGS, "Lista launch configs."),
      createNoInputAction("Recent events", TOOL_NAMES.BRIDGE.EVENTS_RECENT, "Muestra eventos recientes."),
    ],
  },
  {
    id: "home",
    title: "Talend Home",
    description: "Vista inicial con estado del entorno, actividad reciente y accesos rápidos.",
    resourceUri: "ui://talend/home.html",
    launcherToolName: "talend_app_home",
    launchMessage: "Abriendo la pantalla de inicio.",
    uiMode: "react",
    actions: [
      createNoInputAction("Bridge ping", TOOL_NAMES.BRIDGE.PING, "Verifica el bridge."),
      createNoInputAction("List jobs", TOOL_NAMES.JOBS.LIST, "Lista los jobs del proyecto."),
      createNoInputAction("Coverage report", "talend_coverage_report", "Muestra cobertura y gaps."),
    ],
  },
  {
    id: "workspace-explorer",
    title: "Talend Workspace Explorer",
    description: "Explora el workspace, el workbench y el job activo.",
    resourceUri: "ui://talend/workspace-explorer.html",
    launcherToolName: "talend_app_workspace_explorer",
    launchMessage: "Abriendo el explorador de workspace.",
    actions: [
      createNoInputAction("Workbench state", TOOL_NAMES.BRIDGE.WORKBENCH_STATE, "Obtiene el estado del workbench."),
      createNoInputAction("Active job", TOOL_NAMES.STUDIO.PROBABLE_ACTIVE_JOB, "Detecta el job activo probable."),
      createNoInputAction("Open editors", TOOL_NAMES.STUDIO.LIST_OPEN_EDITORS, "Lista editores abiertos."),
    ],
  },
  {
    id: "context-profiles",
    title: "Talend Context Profiles",
    description: "Gestiona perfiles de contexto, variables y cambios asociados.",
    resourceUri: "ui://talend/context-profiles.html",
    launcherToolName: "talend_app_context_profiles",
    launchMessage: "Abriendo los perfiles de contexto.",
    actions: [
      createNoInputAction("List project contexts", TOOL_NAMES.CONTEXTS.LIST_PROJECT, "Lista contextos del proyecto."),
      createNoInputAction("List context profiles", TOOL_NAMES.CONTEXTS.PROFILE_LIST, "Lista perfiles de contexto."),
      createTextAction("Get profile", TOOL_NAMES.CONTEXTS.PROFILE_GET, "Obtiene un perfil de contexto.", "profileName", { inputLabel: "Profile name", inputPlaceholder: "Default" }),
      createJsonAction("Apply to job", TOOL_NAMES.CONTEXTS.PROFILE_APPLY_TO_JOB, "Aplica un perfil a una spec de job.", { profileName: "Default", jobSpec: {} }),
    ],
  },
  {
    id: "database-connection-wizard",
    title: "Talend Database Connection Wizard",
    description: "Asistente para conexiones a bases de datos y componentes disponibles.",
    resourceUri: "ui://talend/database-connection-wizard.html",
    launcherToolName: "talend_app_database_connection_wizard",
    launchMessage: "Abriendo el asistente de conexión a base de datos.",
    actions: [
      createJsonAction("Build connection profile", "talend_connection_build_profile", "Construye un perfil de conexión.", { connectionType: "postgresql", host: "localhost", port: 5432, database: "mydb", user: "admin" }),
      createJsonAction("Add connection", "talend_add_connection", "Agrega una conexión entre componentes.", { jobName: "myJob", sourceUniqueName: "tInput_1", targetUniqueName: "tMap_1", label: "row", connectorName: "FLOW", metaname: "", uniqueName: "connection_1" }, { requiresConfirmation: true }),
      createJsonAction("Update schema column", "talend_update_schema_column", "Actualiza una columna de schema.", { jobName: "myJob", uniqueName: "tMysqlOutput_1", schemaName: "Schema", columnName: "id", patch: { type: "id_Integer" } }, { requiresConfirmation: true }),
    ],
  },
  {
    id: "secret-safety",
    title: "Talend Secret Safety",
    description: "Escanea el proyecto en busca de secretos expuestos y sugiere migraciones a context profiles.",
    resourceUri: "ui://talend/secret-safety.html",
    launcherToolName: "talend_app_secret_safety",
    launchMessage: "Abriendo el scanner de secretos.",
    uiMode: "react",
    actions: [
      createNoInputAction("Scan project", TOOL_NAMES.SECRETS.SCAN_PROJECT, "Escanea todo el proyecto en busca de secretos expuestos."),
      createTextAction("Scan job", TOOL_NAMES.SECRETS.SCAN_JOB, "Escanea un job específico.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
      createTextAction("Suggest context migration", TOOL_NAMES.SECRETS.SUGGEST_CONTEXT_MIGRATION, "Sugiere cómo migrar secretos a context profiles.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
    ],
  },
  {
    id: "requirement-checklist",
    title: "Talend Requirement Checklist",
    description: "Gestiona requisitos técnicos y checklist de cumplimiento.",
    resourceUri: "ui://talend/requirement-checklist.html",
    launcherToolName: "talend_app_requirement_checklist",
    launchMessage: "Abriendo el checklist de requisitos.",
    uiMode: "react",
    actions: [
      createTextAction("Analyze requirements", TOOL_NAMES.REQUIREMENTS.ANALYZE, "Analiza requisitos del proyecto.", "projectPath", { inputLabel: "Project path", inputPlaceholder: "/path/to/project" }),
      createJsonAction("Build checklist", TOOL_NAMES.REQUIREMENTS.BUILD_CHECKLIST, "Construye checklist de requisitos.", { requirements: [] }),
    ],
  },
  {
    id: "workshop-progress",
    title: "Talend Workshop Progress",
    description: "Seguimiento de progreso en workshops y ejercicios.",
    resourceUri: "ui://talend/workshop-progress.html",
    launcherToolName: "talend_app_workshop_progress",
    launchMessage: "Abriendo el progreso de workshop.",
    uiMode: "react",
    actions: [
      createNoInputAction("List workshops", TOOL_NAMES.JOBS.LIST, "Lista workshops disponibles."),
      createTextAction("Get progress", TOOL_NAMES.RUNS.LIST, "Obtiene progreso de un workshop.", "workshopId", { inputLabel: "Workshop id", inputPlaceholder: "workshop_001" }),
    ],
  },
  {
    id: "antipattern-detector",
    title: "Talend Antipattern Detector",
    description: "Detecta antipatrones en jobs y diseño de pipelines.",
    resourceUri: "ui://talend/antipattern-detector.html",
    launcherToolName: "talend_app_antipattern_detector",
    launchMessage: "Abriendo el detector de antipatrones.",
    uiMode: "react",
    actions: [
      createTextAction("Detect antipatterns", TOOL_NAMES.JOBS.DETECT_ANTIPATTERNS, "Detecta antipatrones en jobs.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
      createNoInputAction("Scan project", TOOL_NAMES.JOBS.DETECT_ANTIPATTERNS, "Escanea todo el proyecto."),
    ],
  },
  {
    id: "fix-wizard",
    title: "Talend Fix Wizard",
    description: "Asistente para aplicar fixes automáticos a jobs.",
    resourceUri: "ui://talend/fix-wizard.html",
    launcherToolName: "talend_app_fix_wizard",
    launchMessage: "Abriendo el asistente de fixes.",
    uiMode: "react",
    actions: [
      createTextAction("Explain error", TOOL_NAMES.ERRORS.EXPLAIN, "Sugiere un fix para un error.", "errorMessage", { inputLabel: "Error message", inputPlaceholder: "NullPointerException" }),
      createTextAction("Apply fix", TOOL_NAMES.JOBS.PATCH_COMPONENT, "Aplica un fix sugerido.", "fixId", { inputLabel: "Fix id", inputPlaceholder: "fix_001", requiresConfirmation: true }),
    ],
  },
  {
    id: "evidence-pack",
    title: "Talend Evidence Pack",
    description: "Genera paquetes de evidencia para auditorías y entregas.",
    resourceUri: "ui://talend/evidence-pack.html",
    launcherToolName: "talend_app_evidence_pack",
    launchMessage: "Abriendo el generador de evidence pack.",
    uiMode: "react",
    actions: [
      createTextAction("Build evidence pack", TOOL_NAMES.EVIDENCE.PACK_BUILD, "Construye un paquete de evidencia.", "jobName", { inputLabel: "Job name", inputPlaceholder: "myJob" }),
      createTextAction("Export evidence", TOOL_NAMES.EVIDENCE.PACK_BUILD, "Exporta el evidence pack.", "packId", { inputLabel: "Pack id", inputPlaceholder: "pack_001" }),
    ],
  },
  {
    id: "report-snippets",
    title: "Talend Report Snippets",
    description: "Colección de snippets para generar reportes.",
    resourceUri: "ui://talend/report-snippets.html",
    launcherToolName: "talend_app_report_snippets",
    launchMessage: "Abriendo el gestor de snippets de reporte.",
    uiMode: "react",
    actions: [
      createTextAction("Get snippet", TOOL_NAMES.REPORT.SNIPPETS_GENERATE, "Obtiene un snippet de reporte.", "snippetId", { inputLabel: "Snippet id", inputPlaceholder: "snippet_001" }),
      createTextAction("List snippets", TOOL_NAMES.REPORT.SNIPPETS_GENERATE, "Lista snippets disponibles.", "category", { inputLabel: "Category", inputPlaceholder: "validation" }),
    ],
  },
  {
    id: "component-inspector",
    title: "Talend Component Inspector",
    description: "Inspecciona componentes instalados y sus propiedades en detalle.",
    resourceUri: "ui://talend/component-inspector.html",
    launcherToolName: "talend_app_component_inspector",
    launchMessage: "Abriendo el inspector de componentes.",
    uiMode: "react",
    actions: [
      createTextAction("Scan installed", TOOL_NAMES.COMPONENTS.SCAN_INSTALLED, "Escanea componentes instalados.", "pluginsDir", { inputLabel: "Plugins dir", inputPlaceholder: "Ruta a plugins de Talend Studio" }),
      createTextAction("Search component", TOOL_NAMES.COMPONENTS.SEARCH, "Busca componentes en el catálogo.", "query", { inputLabel: "Query", inputPlaceholder: "mysql" }),
      createTextAction("Inspect component", TOOL_NAMES.COMPONENTS.INSPECT, "Inspecciona un componente.", "componentName", { inputLabel: "Component name", inputPlaceholder: "tMysqlInput" }),
    ],
  },
];
