export const LEGACY_TO_CANONICAL: Array<[string, string]> = [
  ["talend_list_jobs", "talend_jobs_list"],
  ["talend_read_job", "talend_jobs_read"],
  ["talend_dataset_inspect_csv_folder", "talend_datasets_inspect_csv_folder"],
  ["talend_dataset_infer_csv_schema", "talend_datasets_infer_csv_schema"],
  ["talend_dataset_generate_raw_table_mappings", "talend_datasets_generate_raw_mappings"],
  ["talend_snapshot_list", "talend_snapshots_list"],
  ["talend_snapshot_read", "talend_snapshots_read"],
  ["talend_snapshot_restore", "talend_snapshots_restore"],
  ["talend_deliverable_create_package", "talend_deliverables_create_package"],
  ["talend_deliverable_collect_files", "talend_deliverables_collect"],
  ["talend_secret_scan_project", "talend_secrets_scan_project"],
  ["talend_secret_scan_job", "talend_secrets_scan_job"],
  ["talend_secret_suggest_context_migration", "talend_secrets_suggest_context_migration"],
  ["talend_requirements_analyze", "talend_task_analyze_requirements"],
  ["talend_requirements_build_checklist", "talend_task_build_execution_plan"],
  ["talend_antipattern_scan_project", "talend_jobs_detect_antipatterns"],

  ["talend_list_runs", "talend_runs_list"],
  ["talend_read_run", "talend_runs_read"],
  ["talend_run_job", "talend_runs_start"],
  ["talend_run_exported_job", "talend_runs_start_exported"],

  ["talend_error_explain", "talend_errors_explain"],
  ["talend_error_suggest_fix", "talend_errors_suggest_fix"],
  ["talend_error_stats", "talend_errors_stats"],
  ["talend_fix_suggest", "talend_errors_suggest_fix"],

  ["talend_job_validate_design", "talend_validation_validate_design"],
  ["talend_job_validate_context_usage", "talend_validation_validate_context_usage"],
  ["talend_job_validate_audit_columns", "talend_validation_validate_audit_columns"],
  ["talend_job_validate_performance_settings", "talend_validation_validate_performance"],

  ["talend_report_snippet_get", "talend_report_snippets_generate"],
  ["talend_report_snippet_list", "talend_report_snippets_list"],
  ["talend_analyze_job", "analyze_talend_job"],
];
